# Généré par desktop/scripts/package-manifests.mjs — ne pas modifier à la main.
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Certyneo.Reader
PackageVersion: 1.5.2
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: b5d30585-a52b-58f3-9759-de590cbb1e38
FileExtensions:
- pdf
- cndoc
- docx
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.5.2-offline-x64.exe
  InstallerSha256: DA182763AC97ADC69E37DCB6DDB86486A1ADB6CF7108EB912DF2B40E0EE997F4
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.5.2-offline-x64.exe
  InstallerSha256: DA182763AC97ADC69E37DCB6DDB86486A1ADB6CF7108EB912DF2B40E0EE997F4
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  Scope: user
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.5.2-offline-arm64.exe
  InstallerSha256: 00B060DF72F1F3C4E26536062E00004A98E94B48AD6BB586A7B3C27E8BD6F5F0
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.5.2-offline-arm64.exe
  InstallerSha256: 00B060DF72F1F3C4E26536062E00004A98E94B48AD6BB586A7B3C27E8BD6F5F0
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.10.0
