# Généré par desktop/scripts/package-manifests.mjs — ne pas modifier à la main.
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Certyneo.Reader
PackageVersion: 1.5.3
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: b5d30585-a52b-58f3-9759-de590cbb1e38
FileExtensions:
- pdf
- cndoc
- docx
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.5.3-offline-x64.exe
  InstallerSha256: C6DF06FB5B9EEF7AC9ED37FDE5A15502F898107EFAAF573A9EF6B3309D7C6747
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.5.3-offline-x64.exe
  InstallerSha256: C6DF06FB5B9EEF7AC9ED37FDE5A15502F898107EFAAF573A9EF6B3309D7C6747
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  Scope: user
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.5.3-offline-arm64.exe
  InstallerSha256: 3CA8A6A8BC66E0C36D91AF992E8411A77B55EC2F147E46B262515EBD18047D94
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.5.3-offline-arm64.exe
  InstallerSha256: 3CA8A6A8BC66E0C36D91AF992E8411A77B55EC2F147E46B262515EBD18047D94
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.10.0
