# Généré par desktop/scripts/package-manifests.mjs — ne pas modifier à la main.
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Certyneo.Reader
PackageVersion: 1.4.1
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: b5d30585-a52b-58f3-9759-de590cbb1e38
FileExtensions:
- pdf
- cndoc
- docx
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.4.1-offline-x64.exe
  InstallerSha256: D4B7F8E01D9C5808FA5DC017A3ADBC3C698DBABBC2721805DB73C715C5B84479
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.4.1-offline-x64.exe
  InstallerSha256: D4B7F8E01D9C5808FA5DC017A3ADBC3C698DBABBC2721805DB73C715C5B84479
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  Scope: user
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.4.1-offline-arm64.exe
  InstallerSha256: 84812894E8E07F0DA74A08AFD12FD88D042D2223DC2640F7F5121E426811F780
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://certyneo.com/downloads/desktop/Certyneo-Reader-Setup-1.4.1-offline-arm64.exe
  InstallerSha256: 84812894E8E07F0DA74A08AFD12FD88D042D2223DC2640F7F5121E426811F780
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.10.0
